// Automatically generated by astro-icon
// ff13ad40b1e5876af60aae34382f302bd32c8ad62dace3fbf3ed04c63d362473

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow"
		| "baggage"
		| "email"
		| "game"
		| "home"
		| "logo"
		| "phone"
		| "plus-icon"
		| "project"
		| "protect"
		| "star"
		| "users"
		| "youtube";
}