// Automatically generated by astro-icon
// 39ee1c6552dc8792a6d6d75d40bca9690f10e1cd0140337e1d478aa7aa6f53bd

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow"
		| "baggage"
		| "email"
		| "facebook"
		| "game"
		| "home"
		| "instagram"
		| "logo"
		| "phone"
		| "plus-icon"
		| "project"
		| "protect"
		| "star"
		| "users"
		| "youtube";
}