// Automatically generated by astro-icon
// 4d6a59871a56698478d75fa9653ffc1ce41ba110d3d352a91e24fa0131e24ae5

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow"
		| "baggage"
		| "email"
		| "game"
		| "home"
		| "logo"
		| "phone"
		| "plus-icon"
		| "project"
		| "protect"
		| "star"
		| "users";
}